### ISSUE TITLE
Add cpu_constraints and cpu_exclusions to kernel_module

### ISSUE THREAD

**Issue by erman-dev** [erman-dev/kernel-modules-ansible#2]
Do struktury kernel modulů by se mohl přidat attribute cpu_constraints a cpu_exclusions. Ten by se pak používal k rozhodování v roli insert_kernel_module. Pokud by cílový systém neměl požadovanou cpu family, nebo model, tak by se modul nezasunul. Podobně pro cpu_exclusions, pokud by procesor měl danou family/model, tak by se modul nezasunul.

Příklad
```yaml
name: amd_energy
cpu_contraints:
- family: 19h
  models:
  - 10h-19h
  - 21h-27h
- family: 27h
  models:
  - 17h
- family: 28h
cpu_exclusions:
- family: 28h
  models:
  - 02h
```

Není to povinný atribut
```yaml
name: amd_hsmp
```

Nebo ty intervaly mohou být otevřené
```yaml
name: amd_energy
cpu_contraints:
- family: 19h
  models:
  - "-19h"
  - "21h-"
- family: 27h
  models:
  - 17h
- family: 28h
cpu_exclusions:
- family: 28h
  models:
  - 02h
```
